//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long Id { get; set; }
        public long FK_ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string FK_UserId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Quantity { get; set; }
        public double AverageReview { get; set; }
        public byte[] Image { get; set; }
        public long FK_LocationId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
